// flex-theme/packages/react-components/src/components/ThemeToggle/ThemeToggle.tsx
import React from 'react';
import { useFlexTheme } from 'flex-theme/react';
import type { Theme } from 'flex-theme';

export interface ThemeToggleProps extends Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'onChange'> {
  /**
   * Icon to display for light theme
   * @default '☀️'
   */
  lightIcon?: React.ReactNode;
  
  /**
   * Icon to display for dark theme
   * @default '🌙'
   */
  darkIcon?: React.ReactNode;
  
  /**
   * Icon to display for auto theme
   * @default '⚙️'
   */
  autoIcon?: React.ReactNode;
  
  /**
   * Whether to show the theme label
   * @default false
   */
  showLabel?: boolean;
  
  /**
   * Whether to cycle through themes (light -> dark -> auto)
   * @default false
   */
  cycleThemes?: boolean;
  
  /**
   * Callback when theme changes
   */
  onChange?: (theme: Theme) => void;
  
  /**
   * Button variant
   * @default 'icon'
   */
  variant?: 'icon' | 'button' | 'select';
}

/**
 * ThemeToggle component with theme support
 */
export const ThemeToggle: React.FC<ThemeToggleProps> = ({
  lightIcon = '☀️',
  darkIcon = '🌙',
  autoIcon = '⚙️',
  showLabel = false,
  cycleThemes = false,
  onChange,
  variant = 'icon',
  className = '',
  ...props
}) => {
  const { theme, resolvedTheme, setTheme } = useFlexTheme();
  
  // Get the current icon based on theme
  const getIcon = () => {
    if (theme === 'auto') return autoIcon;
    return resolvedTheme === 'light' ? lightIcon : darkIcon;
  };
  
  // Get the current label based on theme
  const getLabel = () => {
    if (theme === 'auto') return 'Auto';
    return resolvedTheme === 'light' ? 'Light' : 'Dark';
  };
  
  // Handle theme change
  const handleThemeChange = (newTheme: Theme) => {
    setTheme(newTheme);
    onChange?.(newTheme);
  };
  
  // Handle button click
  const handleClick = () => {
    if (cycleThemes) {
      // Cycle through light -> dark -> auto
      const nextTheme: Theme = 
        theme === 'light' ? 'dark' : 
        theme === 'dark' ? 'auto' : 'light';
      
      handleThemeChange(nextTheme);
    } else {
      // Toggle between light and dark
      handleThemeChange(resolvedTheme === 'light' ? 'dark' : 'light');
    }
  };
  
  // Handle select change
  const handleSelectChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    handleThemeChange(e.target.value as Theme);
  };
  
  // Base classes
  const baseClasses = 'flex-theme-toggle';
  
  // Variant classes
  const variantClasses = `flex-theme-toggle--${variant}`;
  
  // Theme classes
  const themeClasses = `flex-theme-toggle--theme-${resolvedTheme}`;
  
  // Combine all classes
  const combinedClasses = [
    baseClasses,
    variantClasses,
    themeClasses,
    className
  ].filter(Boolean).join(' ');
  
  // Render based on variant
  if (variant === 'select') {
    return (
      <div className={combinedClasses} data-theme={resolvedTheme}>
        <select
          value={theme}
          onChange={handleSelectChange}
          className="flex-theme-toggle__select"
          aria-label="Select theme"
          {...props}
        >
          <option value="light">Light</option>
          <option value="dark">Dark</option>
          <option value="auto">Auto (System)</option>
        </select>
      </div>
    );
  }
  
  // For icon and button variants
  return (
    <button
      type="button"
      onClick={handleClick}
      className={combinedClasses}
      aria-label={`Switch to ${resolvedTheme === 'light' ? 'dark' : 'light'} theme`}
      data-theme={resolvedTheme}
      {...props}
    >
      <span className="flex-theme-toggle__icon">{getIcon()}</span>
      {showLabel && <span className="flex-theme-toggle__label">{getLabel()}</span>}
    </button>
  );
};

// flex-theme/packages/svelte/src/ThemeToggle.svelte
<script lang="ts">
  import { theme, resolvedTheme, setTheme, toggleTheme, t } from './stores';
  
  // Props
  export let lightIcon = '☀️';
  export let darkIcon = '🌙';
  export let autoIcon = '⚙️';
  export let showLabel = false;
  export let cycleThemes = false;
  export let variant: 'icon' | 'button' | 'select' = 'icon';
  
  // Computed values
  $: icon = $theme === 'auto' ? autoIcon : $resolvedTheme === 'light' ? lightIcon : darkIcon;
  $: label = $theme === 'auto' ? 'Auto' : $resolvedTheme === 'light' ? 'Light' : 'Dark';
  $: ariaLabel = cycleThemes 
    ? `Current theme: ${label}. Click to cycle themes.`
    : `Switch to ${$resolvedTheme === 'light' ? 'dark' : 'light'} theme`;
  
  // Handle click
  function handleClick() {
    if (cycleThemes) {
      // Cycle through light -> dark -> auto
      if ($theme === 'light') {
        setTheme('dark');
      } else if ($theme === 'dark') {
        setTheme('auto');
      } else {
        setTheme('light');
      }
    } else {
      toggleTheme();
    }
  }
</script>

{#if variant === 'select'}
  <div class="flex-theme-toggle flex-theme-toggle--select" data-theme={$resolvedTheme}>
    <select
      value={$theme}
      on:change={(e) => setTheme(e.target.value)}
      class="flex-theme-toggle__select"
      aria-label="Select theme"
    >
      <option value="light">{t('themes.light')}</option>
      <option value="dark">{t('themes.dark')}</option>
      <option value="auto">{t('themes.auto')}</option>
    </select>
  </div>
{:else}
  <button
    type="button"
    on:click={handleClick}
    class="flex-theme-toggle flex-theme-toggle--{variant}"
    aria-label={ariaLabel}
    data-theme={$resolvedTheme}
  >
    <span class="flex-theme-toggle__icon">{icon}</span>
    {#if showLabel}
      <span class="flex-theme-toggle__label">{label}</span>
    {/if}
  </button>
{/if}

<style>
  .flex-theme-toggle {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s ease;
  }
  
  .flex-theme-toggle--icon {
    background: transparent;
    border: none;
    padding: 0.5rem;
    border-radius: 9999px;
    cursor: pointer;
    color: var(--color-textPrimary, inherit);
  }
  
  .flex-theme-toggle--icon:hover {
    background-color: rgba(0, 0, 0, 0.05);
  }
  
  :global([data-theme="dark"]) .flex-theme-toggle--icon:hover {
    background-color: rgba(255, 255, 255, 0.1);
  }
  
  .flex-theme-toggle--button {
    background-color: var(--color-surface, #f8f9fa);
    border: 1px solid var(--color-border, #e0e0e0);
    padding: 0.5rem 1rem;
    border-radius: 0.25rem;
    cursor: pointer;
    color: var(--color-textPrimary, inherit);
  }
  
  .flex-theme-toggle--button:hover {
    background-color: var(--color-surfaceVariant, #f0f0f0);
  }
  
  :global([data-theme="dark"]) .flex-theme-toggle--button {
    background-color: var(--color-surface, #1e1e1e);
    border-color: var(--color-border, #333333);
  }
  
  :global([data-theme="dark"]) .flex-theme-toggle--button:hover {
    background-color: var(--color-surfaceVariant, #2a2a2a);
  }
  
  .flex-theme-toggle--select {
    position: relative;
  }
  
  .flex-theme-toggle__select {
    appearance: none;
    background-color: var(--color-surface, #f8f9fa);
    border: 1px solid var(--color-border, #e0e0e0);
    padding: 0.5rem 2rem 0.5rem 1rem;
    border-radius: 0.25rem;
    cursor: pointer;
    color: var(--color-textPrimary, inherit);
    background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='6 9 12 15 18 9'%3E%3C/polyline%3E%3C/svg%3E");
    background-repeat: no-repeat;
    background-position: right 0.5rem center;
    background-size: 1em;
  }
  
  :global([data-theme="dark"]) .flex-theme-toggle__select {
    background-color: var(--color-surface, #1e1e1e);
    border-color: var(--color-border, #333333);
  }
  
  .flex-theme-toggle__label {
    margin-left: 0.5rem;
  }
  
  @media (prefers-reduced-motion: reduce) {
    .flex-theme-toggle {
      transition: none;
    }
  }
</style>
